#!/usr/bin/env sh

set -e

env=${APP_ENV:-production}
role=${CONTAINER_ROLE:-app}
laravel=${LARAVEL_TYPE:-laravel}

echo "The env is ${env}"

# Run PHP-FPM as current user
if [ ! -z "$APP_USER" ]; then
    sed -i "s/65534/$APP_USER/g" /etc/passwd
fi

if [ ! -z "$APP_USER_GROUP" ]; then
    sed -i "s/65534/$APP_USER_GROUP/g" /etc/group
fi

# Cache configuration
if [ "$env" != "local" && "$laravel" == "laravel" ]; then
    echo "Caching configuration"
    (
        php artisan config:cache &&
        php artisan view:cache &&
        php artisan route:cache
    )

# Enable development features.
else
    sed -i "s/opcache.validate_timestamps=0/opcache.validate_timestamps=1/g" /etc/php7/conf.d/opcache.ini

fi

if [ "$role" = "app" ]; then
    cd ~/ && /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf

elif [ "$role" = "queue" ]; then
    sudo -u nobody php artisan horizon
    exit 1e

elif [ "$role" = "scheduler" ]; then
    while [ true ]
    do
      sudo -u nobody php artisan schedule:run --verbose --no-interaction &
      sleep 60
    done

    exit 1

else
    echo "Could not match the container role \"$role\""
    exit 1
fi
